spring.profile:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EnSunny/spring-kafka-msa.git
          search-paths:
            - "EmailServiceConfigProperties/{application}/{profile}"